x-default-opts: &default-opts
  restart: unless-stopped
  tty: true
  stdin_open: true
  privileged: false
  ipc: private
  
services:
  web:
    <<: *default-opts
    build: 
      context: .
      dockerfile: dockerfile
    container_name: linux-lab-markdown
    volumes:
      - "./:/home/user/app"
    ports:
      - "3000:3000"
    command: sh -c "cd /home/user/app && docsify serve docs -p 3000"