x-default-opts: &default-opts
  restart: always
  tty: true
  stdin_open: true
  privileged: false
  ipc: private
  
services:
  nginx:
    <<: *default-opts
    build: 
      context: .
      dockerfile: dockerfile
    container_name: linux-lab-markdown
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    command: sh -c "cd /app && docsify serve docs -p 3000"